openapi: 3.0.3
info:
  title: KomMonitor Spatial Data Processor API
  description: |-
    API zur Verarbeitung von räumlichen Daten aus dem KomMonitor-Ökosystem.
  contact:
    email: j.speckamp@52north.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1

servers:
  - url: http://localhost:8090/

tags:
  - name: processes
    description: Processes that can be executed by this processor
  - name: jobs
    description: Jobs that are being processed

paths:
  /processes:
    get:
      tags:
        - processes
      description: Returns a list of all available Processes
      summary: Returns a list of all available Processes
      operationId: getAllProcessDescriptions
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessOverviewType'
        '401':
          description: unauthorized
      security:
        - kommonitor_auth:
            - access:spatial-data-processor

  /jobs:
    get:
      tags:
        - jobs
      description: Returns a list of all currently queued jobs
      summary: Returns a list of all currently queued jobs
      operationId: getAllJobs
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobOverviewType'
        '401':
          description: unauthorized
      security:
        - kommonitor_auth:
            - access:spatial-data-processor

    post:
      tags:
        - jobs
      summary: Submits a processing Job for execution
      description: Submits a processing Job for execution
      operationId: enqueueJob
      requestBody:
        description: Definition of Job to be executed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessType'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                format: uuid
                description: UUID of the Job created
        '401':
          description: unauthorized
        '405':
          description: Invalid input
      security:
        - kommonitor_auth:
            - access:spatial-data-processor

  /jobs/{jobId}:
    get:
      tags:
        - jobs
      summary: Gets the current status of a job
      description: Gets the current status of a job
      operationId: getJob
      parameters:
        - in: path
          name: jobId
          required: true
          description: UUID of the job
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobOverviewType'
        '401':
          description: unauthorized
        '404':
          description: Job not found
      security:
        - kommonitor_auth:
            - access:spatial-data-processor

  /jobs/{jobId}/result:
    get:
      tags:
        - jobs
      summary: Gets the result of a job
      description: Gets the result of a job
      operationId: getJobResult
      parameters:
        - in: path
          name: jobId
          required: true
          description: UUID of the job
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobResultType'
        '401':
          description: unauthorized
        '404':
          description: Job not found
      security:
        - kommonitor_auth:
            - access:spatial-data-processor

components:
  schemas:
    ProcessOverviewType:
      description: Description of a Process that can be executed by the processor
      type: object
      required:
        - id
        - name
        - description
      properties:
        id:
          $ref: '#/components/schemas/uuid'
        name:
          type: string
        description:
          type: string

    ProcessType:
      description: POST type for a new job to be executed by the processor
      type: object
      discriminator:
        propertyName: name
        mapping:
          isochrone-prune: '#/components/schemas/IsochronePruneProcessType'
          test: '#/components/schemas/TestProcessType'
      oneOf:
        - $ref: "#/components/schemas/IsochronePruneProcessType"
        - $ref: "#/components/schemas/TestProcessType"

    IsochronePruneProcessType:
      description: > 
        Process that calculates overlap of spatial-units with isochrones to determine an accessibility rate for certain
        indicators.
      type: object
      required:
          - name
          - isochron
          - spatialUnit
          - indicator
          - configuration
      properties:
        name:
          type: string
          default: "isochrone-prune"
          description: >
            Unique name of the process. Will be used to determine which process will be triggered server-side.
        isochrones:
          description: >
            Isochrones as GeoJSON FeatureCollection
          $ref: "#/components/schemas/FeatureCollectionType"
        spatialUnit:
          type: string
          format: uuid
          description: >
            Unique identifier of the spatial unit. This ID will be used to fetch spatial unit data from the 
            KomMonitor DataManagement API.
        indicator:
          type: array
          items:
            type: string
            format: uuid
          description: >
            List of unique indicator identifiers. These IDs will be used to fetch indicator timeseries data from the 
            KomMonitor DataManagement API.
        date:
          type: string
          format: date
          description: >
            Defines the date for which indicator timeseries data will be fetched from DataManagement API.
        weighting:
          type: string
          enum: [ simple, residential_areas ]
          description: |
            Method to use for weighting intersections of spatial units and isochrones:
             * `simple` - No weighting will be applied, which means that intersection proportions are returned as is.
             * `residential_areas` - Residential areas are additionally considered to calculate an intersection proportion.

    TestProcessType:
      description: Process for testing the API.
      type: object
      required:
          - name
          - test
      properties:
        name:
          type: string
          default: "test"
          description: >
            Unique name of the process. Will be used to determine which process will be triggered server-side.
        test:
          type: string
          description: >
            Just a dummy test parameter.

    FeatureCollectionType:
      description: Generic type as container for GeoJSON FeatureCollections
      type: object
      #TODO: expand with actual schema

    JobOverviewType:
      description: Description of a Job
      type: object
      required:
        - id
        - process
        - timestamp
        - status
      properties:
        id:
          $ref: '#/components/schemas/uuid'
        process:
          type: string
          description: >
            Name of the process that will be executed by this job.
        timestamp:
          type: string
          format: date-time
          description:
            Timestamp for job execution start.
        status:
          type: string
          enum: [ queued, running, finished, failed ]
          description: |
            Indicates the execution status of a job:
             * `queued` - The job has been created but process execution has not started, yet.
             * `running` - Process execution has started.
             * `finished` - Process execution has finished.
             * `failed` - The job failed due to an error during process execution.

    JobResultType:
      type: object
      required:
            - id
            - result
      properties:
        id:
          $ref: '#/components/schemas/uuid'
          description: >
            Unique job ID
        result:
          type: object
          description: >
            Result of the process execution. The result is a JSON object whose schema depends on the underlying process.
            Each process has its own result schema.
            
    IsochronePruneProcessResultType:
      type: object
      required:
        - indicatorId
      properties:
        indicatorId:
          type: string
          format: uuid
          description: >
            Unique indicator identifier. Coverage values relates to this indicator.
        overallCoverage:
          type: array
          items:
            $ref: '#/components/schemas/OverallCoverageType'
          description: >
            Indicates coverages for the entire spatial unit, which means the coverage of all isochrones of a certain 
            range together for all spatial unit features.
        poiCoverage:
          type: array
          items:
            $ref: '#/components/schemas/PoiCoverageType'
          description: >
            Indicates single isochron coverages for each spatial unit.

    PoiCoverageType:
      type: object
      required:
        - poiFeatureId
      properties:
        poiFeatureId:
          type: string
        overallCoverage:
          type: array
          items:
            $ref: '#/components/schemas/IndicatorCoverageValueType'
          description: >
            Indicates the coverage for the entire spatial unit, which means the coverage of a single isochron for
            all spatial unit features.
        spatialUnitCoverage:
          type: array
          items:
            $ref: '#/components/schemas/SpatialUnitCoverageType'
          description: >
            Indicates the coverage for single spatial unit features, which means the coverage of a single isochron for
            each feature of a spatial unit.

    SpatialUnitCoverageType:
      type: object
      required:
        - spatialUnitFeatureId
      properties:
        spatialUnitFeatureId:
          type: string
          description: >
            Unique identifier for the spatial unit. This ID can be used to identify a spatial unit at the 
            DataManagement API.
        coverage:
          type: array
          items:
            $ref: '#/components/schemas/IndicatorCoverageValueType'
          description: >
            Indicator coverage for this spatial unit.

    OverallCoverageType:
      type: object
      required:
        - range
      properties:
        range:
          type: number
          format: float
          description: >
            Indicates the isochron range that relates to the indicator coverage values.
        coverage:
          type: array
          items:
            $ref: '#/components/schemas/IndicatorCoverageValueType'
          description: >
            The coverage values of an isochron for a certain indicator.

    IndicatorCoverageValueType:
      type: object
      properties:
        date:
          type: string
          format: date
          description: >
            Indicates for which indicator timeseries date the coverage values relate to.
        absoluteCoverage:
          type: number
          format: float
          description: >
            Absolute indicator coverage value. This value is calculated by multiplying the relative coverage with
            the indicator value.
        relativeCoverage:
          type: number
          format: float
          description: >
            Relative indicator coverage value. This value is calculated by determining the proportion of intersection
            of an isochron geometry with spatial unit feature geometries.

    uuid:
      type: string
      format: uuid
      description: Unique ID

  securitySchemes:
    kommonitor_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://keycloak:8080/auth
          tokenUrl: http://keycloak:8080/auth/realms/kommonitor/protocol/openid-connect/token
          scopes: {}

security:
  - oAuthNoScopes: []
