/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.n52.kommonitor.spatialdataprocessor.api;

import org.n52.kommonitor.models.ProcessOverviewType;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-06-08T22:37:08.978103200+02:00[Europe/Berlin]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "processes", description = "Processes that can be executed by this processor")
public interface ProcessesApi {

    String PATH_GET_ALL_PROCESS_DESCRIPTIONS = "/processes";
    /**
     * GET /processes : Returns a list of all available Processes
     * Returns a list of all available Processes
     *
     * @return success (status code 200)
     *         or unauthorized (status code 401)
     */
    @Operation(
        operationId = "getAllProcessDescriptions",
        summary = "Returns a list of all available Processes",
        description = "Returns a list of all available Processes",
        tags = { "processes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "success", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ProcessOverviewType.class)))
            }),
            @ApiResponse(responseCode = "401", description = "unauthorized")
        },
        security = {
            @SecurityRequirement(name = "kommonitor_auth", scopes={ "access:spatial-data-processor" })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProcessesApi.PATH_GET_ALL_PROCESS_DESCRIPTIONS,
        produces = { "application/json" }
    )
    ResponseEntity<List<ProcessOverviewType>> getAllProcessDescriptions(
        
    );

}
